name: Exercise Workflow

on: push


jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: "Install style checker"
        run: pip install black
      - name: "Run style check"
        run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: "Install pytest"
        run: pip install pytest
      - name: "Install dependencies"
        run: pip install numpy matplotlib
      - name: "Run pytest"
        run: python -m pytest
  # build:
  #   needs: style
  #   runs-on: ubuntu-latest
  #   env:
  #     PROJECT_NAME: "Automation Lecture"
  #   steps:

