name: Exercise Workflow

on: push


jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: "Install style checker"
        run: pip install black
      - name: "Run style check"
        run: black --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: "Install dependencies"
        run: pip install numpy matplotlib
      - name: "Install pytest"
        run: pip install pytest
      - name: "Run pytest"
        run: python -m pytest
      - name: "Install coverage"
        run: pip install coverage
      - name: "Run coverage"
        run: coverage run -m pytest
      - name: "Upload coverage report (artifact)"
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: .coverage
          retention-days: 1

  coverage_report:
    needs: test
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "Automation Lecture"
    steps:
      - name: "Download coverage report (artifact)"
        uses: actions/download-artifact@v2
        with:
          name: coverage

      - uses: actions/setup-python@v2
      - name: "Install coverage"
        run: pip install coverage
      - name: "Create coverage report"
        run: coverage report .coverage

